version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: sistema_nutri_php
    working_dir: /var/www/html
    volumes:
      - ../src:/var/www/html
    networks:
      - sistema-nutri-network

  webserver:
    image: nginx:alpine
    container_name: sistema_nutri_nginx
    ports:
      - "8080:80"
    volumes:
      - ../src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - sistema-nutri-network

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistemanutri
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - sistema-nutri-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sistema_nutri_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - sistema-nutri-network

networks:
  sistema-nutri-network:
    driver: bridge

volumes:
  db_data:
